---
title: "R Notebook"
author: "Anna Lam (al5qb)"
date: "November 15, 2018"
output:
  html_document:
    df_print: paged
---

BME 4550 Data Science - Seminar Report 2

On Thursday, November 15, at 9:30am, I attended Dr. Holly A. Ingraham's seminar in Pinn Hall Conference Center (PHCC) Auditorium on the first floor of Pinn Hall. Dr. Holly A. Ingraham, Ph.D. is a professor and the Associate Vice Chair in Cellular and Molecular Pharmacology at The University of California, San Francisco. She is also a Herzstein Distinguished Investigator. 

The seminar Dr. Ingraham presented was "Female Bones and Behaviors Controlled by Sex-Dependent Hypothalamic Nodes." A good majority of the seminar discussed the effect of estrogen in the system and bone density. Estrogen is the primary female sex hormone that is responsible for the development and maintenance of the female body in several aspects. Estrogen, in the human body, will help prevent bone loss, but will not build bone -- unless there are some super-physiological levels of bone. Dr. Ingraham presented to us many pictures showing the differences in bone density between different subjects. Some subjects varied in age, while some varied in gender. She then showed us that if estrogen were removed completely from the system, there would be a difference in bone density and strength. An increase in bone density and strength was only seen, however, in females and not males. Therefore, it is safe to say that this is female-specific. To test the strength of bone, there were two tests that were performed: the 3 Point (Pt) Test and the Crush Test. The 3 Pt Test examined 33 week old female bones in mice, which is considered old, and observed an enormous amount of strength in the mutant. It had more bone and was stronger. Dr. Ingraham even joked that if the bone were any stronger, they would have had to change the parameters of the machine. A research question that Dr. Ingraham had was if input was neural or hormonal. She did RNA sequencing and observed an increase in all natural neural peptides that marked KNDy, a decrease in dopamine signal, and increase in KISS1 (controls puberty in both males and females). Dr. Ingraham also pondered which neuron was mediating bone effect. Even after going through different Cre's, she did not observe any differences (not POMC or DAT). It wasn't until eight to nine months later around January or February, that they started looking at KISS1 Cre. She noted that some Cre's are better than others and that the original KISS1 Cre is very nonspecific. They examined an attenuated KISS Cre and observed far fewer neurons expressing ER??. They realized estrogen was suppressing the KISS neurons, so when they removed estrogen, there was an upregulation of KISS1. Dr. Ingraham then briefly spoke about parabiosis, which is the joining together of two initially separate bodies. When parabiosis was performed on a wild mouse and a mutant mouse so that their circulation fused after two weeks, experimental scans were done at Week three and Week six. They observed that the wild type bone had an increase in bone density, so they knew that there had to be a factor that was increasing bone. The mutant female that was joined with the wild-type started building even more bone as if they were just reaching out for any nutrients they could get to in order to build more bone. Dr. Ingraham showed us an image of bone that had a bone volume of up to 91%, which is incredibly strong, and like nothing that we are used to seeing. 

The take-home message is that the effect of estrogen on bone is female-specific and, from Dr. Ingraham's brief pep talk at the end, young researchers, especially females, should continue to stand up for themselves, compete with peers of old and young and of both gender, and to not succumb. Attending this seminar given by Dr. Ingraham was educational and inspiring. If I could ask Dr. Ingraham two questions about her research, it would be (1) What prompted you to conduct research on bone density and strength, especially with looking at estrogen and its effects?, and (2) If estrogen's effect on bone is female-specific, does testosterone have an effect on bone density as well, and will that be male-specific?
